import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}
// router
// export default function RootLayout ({
//   children,
//   team,
//   analytics
// }: {
//   children: React.ReactNode
//   team?: React.ReactNode
//   analytics?: React.ReactNode
// }) {
//   return (
//     <html lang='en'>
//       <body className={inter.className}>
//         <h1>root layout</h1>
//         {children} {team} {analytics}
//       </body>
//     </html>
//   )
// }

import Link from 'next/link'

export default function RootLayout ({ children, auth }) {
  return (
    <html>
      <body>
        <div>
          <Link href='/login'>Open Auth Modal</Link>
        </div>
        <div>
          <Link href='/'>Back To Home</Link>
        </div>
        <h1>/app/layout.js</h1>
        {children}
        {auth}
      </body>
    </html>
  )
}
